const{getPool}=require("./_db");const{ensureContentSchema,slugify,cleanHtml,adminToken}=require("./_content");
const allowed=(v,l,f)=>l.includes(v)?v:f;
module.exports=async(req,res)=>{if(adminToken(req)!==process.env.ADMIN_TOKEN)return res.status(401).json({ok:false,error:"Unauthorized"});
try{await ensureContentSchema();const pool=getPool();await pool.query("update public.content_posts set status='published',updated_at=now() where status='scheduled' and published_at is not null and published_at<=now()");const fields=`id,slug,title_bn,title_en,excerpt_bn,excerpt_en,body_bn,body_en,category,content_type,country,keywords,status,featured,source_name,source_url,source_verified,importance,image_url,image_alt,image_caption,image_credit,resource_key,ai_generated,ai_confidence,published_at,created_at,updated_at`;
if(req.method==="GET"){const id=Number(req.query?.id||0);if(id){const r=await pool.query(`select ${fields} from public.content_posts where id=$1 limit 1`,[id]);if(!r.rows[0])return res.status(404).json({ok:false,error:"Post not found"});return res.json({ok:true,post:r.rows[0]})}const r=await pool.query(`select ${fields} from public.content_posts order by created_at desc limit 300`);return res.json({ok:true,posts:r.rows})}
const b=typeof req.body==="string"?JSON.parse(req.body||"{}"):(req.body||{}),types=["news","guide","suggestion","prediction","announcement","problem-solution","recent-questions","exam-intelligence","opportunity","outlook"];
const titleBn=String(b.title_bn||"").trim(),titleEn=String(b.title_en||"").trim(),bodyBn=cleanHtml(b.body_bn),bodyEn=cleanHtml(b.body_en);
const countries=String(b.country||"").split(",").map(x=>x.trim()).filter(Boolean).slice(0,3).join(",");
const common=[titleBn||titleEn,titleEn||null,b.excerpt_bn||null,b.excerpt_en||null,bodyBn||bodyEn,bodyEn||null,allowed(b.category,["study-abroad","ielts","pte"],"study-abroad"),allowed(b.content_type,types,"news"),countries||null,b.keywords||null,!!b.featured,b.source_url||null,b.source_name||null,!!b.source_verified,allowed(b.importance,["critical","important","useful","general"],"useful"),b.image_url||null,b.image_alt||null,b.image_caption||null,b.image_credit||null,b.resource_key||null];
if(!(titleBn||titleEn)||!(bodyBn||bodyEn))return res.status(400).json({ok:false,error:"Add a title and article in Bangla or English"});
if(req.method==="POST"){const status=allowed(b.status,["draft","review","scheduled","published","archived"],"draft");const publishAt=status==="scheduled"&&b.publish_at?new Date(b.publish_at):null;if(status==="scheduled"&&(!publishAt||Number.isNaN(publishAt.getTime())||publishAt<=new Date()))return res.status(400).json({ok:false,error:"Choose a future schedule time"});let slug=slugify(b.slug||b.title_en||b.title_bn);if((await pool.query("select 1 from public.content_posts where slug=$1",[slug])).rowCount)slug+="-"+Date.now().toString().slice(-6);
const r=await pool.query(`insert into public.content_posts(slug,title_bn,title_en,excerpt_bn,excerpt_en,body_bn,body_en,category,content_type,country,keywords,featured,source_url,source_name,source_verified,importance,image_url,image_alt,image_caption,image_credit,resource_key,status,published_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,case when $22='published' then now() when $22='scheduled' then $23::timestamptz else null end,now()) returning id,slug,status,published_at`,[slug,...common,status,publishAt?publishAt.toISOString():null]);return res.status(201).json({ok:true,post:r.rows[0]})}
if(req.method==="PATCH"){const id=Number(b.id);if(!id)return res.status(400).json({ok:false,error:"Missing id"});const status=allowed(b.status,["draft","review","scheduled","published","archived"],"draft");const publishAt=status==="scheduled"&&b.publish_at?new Date(b.publish_at):null;if(status==="scheduled"&&(!publishAt||Number.isNaN(publishAt.getTime())||publishAt<=new Date()))return res.status(400).json({ok:false,error:"Choose a future schedule time"});
const r=await pool.query(`update public.content_posts set title_bn=$1,title_en=$2,excerpt_bn=$3,excerpt_en=$4,body_bn=$5,body_en=$6,category=$7,content_type=$8,country=$9,keywords=$10,featured=$11,source_url=$12,source_name=$13,source_verified=$14,importance=$15,image_url=$16,image_alt=$17,image_caption=$18,image_credit=$19,resource_key=$20,status=$21,published_at=case when $21='published' then coalesce(published_at,now()) when $21='scheduled' then $22::timestamptz else null end,updated_at=now() where id=$23 returning id,slug,status,published_at`,[...common,status,publishAt?publishAt.toISOString():null,id]);return res.json({ok:true,post:r.rows[0]})}
if(req.method==="DELETE"){const id=Number(b.id);if(!id)return res.status(400).json({ok:false,error:"Missing id"});await pool.query("delete from public.content_posts where id=$1",[id]);return res.json({ok:true})}
return res.status(405).json({ok:false,error:"Method not allowed"})}catch(e){return res.status(500).json({ok:false,error:String(e?.message||e)})}};