const{getPool}=require("./_db");const{ensureContentSchema,slugify,cleanHtml,adminToken}=require("./_content");
const allowed=(v,l,f)=>l.includes(v)?v:f;
module.exports=async(req,res)=>{if(adminToken(req)!==process.env.ADMIN_TOKEN)return res.status(401).json({ok:false,error:"Unauthorized"});
try{await ensureContentSchema();const pool=getPool(),fields=`id,slug,title_bn,title_en,excerpt_bn,excerpt_en,body_bn,body_en,category,content_type,country,keywords,status,featured,source_name,source_url,source_verified,importance,image_url,image_alt,image_caption,image_credit,resource_key,ai_generated,ai_confidence,published_at,created_at,updated_at`;
if(req.method==="GET"){const id=Number(req.query?.id||0);if(id){const r=await pool.query(`select ${fields} from public.content_posts where id=$1 limit 1`,[id]);if(!r.rows[0])return res.status(404).json({ok:false,error:"Post not found"});return res.json({ok:true,post:r.rows[0]})}const r=await pool.query(`select ${fields} from public.content_posts order by created_at desc limit 300`);return res.json({ok:true,posts:r.rows})}
const b=typeof req.body==="string"?JSON.parse(req.body||"{}"):(req.body||{}),types=["news","guide","suggestion","prediction","announcement","problem-solution"];
const common=[String(b.title_bn||"").trim(),b.title_en||null,b.excerpt_bn||null,b.excerpt_en||null,cleanHtml(b.body_bn),cleanHtml(b.body_en)||null,allowed(b.category,["study-abroad","ielts","pte"],"study-abroad"),allowed(b.content_type,types,"news"),b.country||null,b.keywords||null,!!b.featured,b.source_url||null,b.source_name||null,!!b.source_verified,allowed(b.importance,["critical","important","useful","general"],"useful"),b.image_url||null,b.image_alt||null,b.image_caption||null,b.image_credit||null,b.resource_key||null];
if(!common[0]||!common[4])return res.status(400).json({ok:false,error:"Bangla title and article are required"});
if(req.method==="POST"){const status=allowed(b.status,["draft","review","published","archived"],"draft");let slug=slugify(b.slug||b.title_en||b.title_bn);if((await pool.query("select 1 from public.content_posts where slug=$1",[slug])).rowCount)slug+="-"+Date.now().toString().slice(-6);
const r=await pool.query(`insert into public.content_posts(slug,title_bn,title_en,excerpt_bn,excerpt_en,body_bn,body_en,category,content_type,country,keywords,featured,source_url,source_name,source_verified,importance,image_url,image_alt,image_caption,image_credit,resource_key,status,published_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,case when $22='published' then now() else null end,now()) returning id,slug,status`,[slug,...common,status]);return res.status(201).json({ok:true,post:r.rows[0]})}
if(req.method==="PATCH"){const id=Number(b.id);if(!id)return res.status(400).json({ok:false,error:"Missing id"});const status=allowed(b.status,["draft","review","published","archived"],"draft");
const r=await pool.query(`update public.content_posts set title_bn=$1,title_en=$2,excerpt_bn=$3,excerpt_en=$4,body_bn=$5,body_en=$6,category=$7,content_type=$8,country=$9,keywords=$10,featured=$11,source_url=$12,source_name=$13,source_verified=$14,importance=$15,image_url=$16,image_alt=$17,image_caption=$18,image_credit=$19,resource_key=$20,status=$21,published_at=case when $21='published' and published_at is null then now() when $21<>'published' then null else published_at end,updated_at=now() where id=$22 returning id,slug,status`,[...common,status,id]);return res.json({ok:true,post:r.rows[0]})}
if(req.method==="DELETE"){const id=Number(b.id);if(!id)return res.status(400).json({ok:false,error:"Missing id"});await pool.query("delete from public.content_posts where id=$1",[id]);return res.json({ok:true})}
return res.status(405).json({ok:false,error:"Method not allowed"})}catch(e){return res.status(500).json({ok:false,error:String(e?.message||e)})}};